apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-app
  template:
    metadata:
      labels:
        app: ml-app
    spec:
      containers:
      - name: train-app
        image: train_image
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
        - name: models
          mountPath: "/etc/models"
      - name: predict-app
        image: predict_image
        imagePullPolicy: Never
        ports:
        - containerPort: 8083
        volumeMounts:
        - name: models
          mountPath: "/etc/models"
      volumes:
      - name: models

---

apiVersion: v1
kind: Service
metadata:
    labels:
      app: ml-app
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
    selector:
      app: ml-app
    ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
    type: LoadBalancer
